### ISSUE TITLE
docker healthcheck fails after running for a while

### ISSUE THREAD

**Issue by yingziwu** [zeratax/matrix-registration#100]
### How did you install matrix-registration?

docker

### What version of matrix-registration are you running?

latest (cd89ec899623a7f5ff5ee3d17b8488e990b51b3a)

### Your config.yml

```yaml
server_location: "http://host.docker.internal:8008"
server_name: "xxx.xxxx"
registration_shared_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
admin_api_shared_secret: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
base_url: "/xxxxxxxxxxxxxx" # e.g. '/element' for https://example.tld/element/register
client_redirect: "https://xxx.xxx.xxx/#/login"
client_logo: "static/images/element-logo.png" # use '{cwd}' for current working directory
db: "sqlite:////data/db.sqlite3"
host: "0.0.0.0"
port: 5000
rate_limit: ["100 per day", "10 per minute"]
allow_cors: false
ip_logging: true
logging:
  disable_existing_loggers: false
  version: 1
  root:
    level: DEBUG
    handlers: [console, file]
  formatters:
    brief:
      format: "%(name)s - %(levelname)s - %(message)s"
    precise:
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: INFO
      formatter: brief
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: precise
      level: INFO
      filename: /data/m_reg.log
      maxBytes: 10485760 # 10MB
      backupCount: 3
      encoding: utf8
# password requirements
password:
  min_length: 8
# username requirements
username:
  validation_regex: [] #list of regexes that the selected username must match.        Example: '[a-zA-Z]\.[a-zA-Z]'
  invalidation_regex: ["(admin|support)"] #list of regexes that the selected username must NOT match.  Example: '(admin|support)'
```

### Your error log

docker-compose ps

```
       Name                      Command                   State                         Ports
----------------------------------------------------------------------------------------------------------------
matrix-registration   /nix/store/x0crc62h6fpj4mw ...   Up (unhealthy)   0.0.0.0:5000->5000/tcp,:::5000->5000/tcp
```

docker-compose logs
```
Attaching to matrix-registration
matrix-registration    | waitress - INFO - Serving on http://0.0.0.0:5000
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 10 per 1 minute (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
matrix-registration    | flask-limiter - WARNING - ratelimit 100 per 1 day (127.0.0.1) exceeded at endpoint: api.health
```

```
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 509649,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-01-06T12:23:05.139690909Z",
            "FinishedAt": "0001-01-01T00:00:00Z",
            "Health": {
                "Status": "unhealthy",
                "FailingStreak": 71,
                "Log": [
                    {
                        "Start": "2023-01-06T12:31:15.484026179Z",
                        "End": "2023-01-06T12:31:15.612620284Z",
                        "ExitCode": 22,
                        "Output": "curl: (22) The requested URL returned error: 429\n"
                    },
                    {
                        "Start": "2023-01-06T12:31:18.617774367Z",
                        "End": "2023-01-06T12:31:18.746308621Z",
                        "ExitCode": 22,
                        "Output": "curl: (22) The requested URL returned error: 429\n"
                    },
                    {
                        "Start": "2023-01-06T12:31:21.751324463Z",
                        "End": "2023-01-06T12:31:21.863375834Z",
                        "ExitCode": 22,
                        "Output": "curl: (22) The requested URL returned error: 429\n"
                    },
                    {
                        "Start": "2023-01-06T12:31:24.867536697Z",
                        "End": "2023-01-06T12:31:24.97783731Z",
                        "ExitCode": 22,
                        "Output": "curl: (22) The requested URL returned error: 429\n"
                    },
                    {
                        "Start": "2023-01-06T12:31:27.984076136Z",
                        "End": "2023-01-06T12:31:28.100008885Z",
                        "ExitCode": 22,
                        "Output": "curl: (22) The requested URL returned error: 429\n"
                    }
                ]
            }
        },
        "Image": "sha256:2b77d8f0e234880eb823fe470a87f1160d02d5395c316474d70bfdc956c024ee",
        "ResolvConfPath": "/var/lib/docker/containers/a7a62081e29f0f4d355862d72310ce00648ca312f5ad52d3c30396f17063fdd2/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/a7a62081e29f0f4d355862d72310ce00648ca312f5ad52d3c30396f17063fdd2/hostname",
```

### Area of your issue?

general usage

### What happened

docker healthcheck fails after running for a while

### Steps to reproduce

1. load lastest docker image from github action.
2. start docker container
3. wait for a while
