### ISSUE TITLE
No such option --config-path

### ISSUE THREAD

**Issue by chris-aeviator** [ZerataX/matrix-registration#104]
### How did you install matrix-registration?

docker

### What version of matrix-registration are you running?

0.9.1

### Your error log

```text
no such option `--config-path`
```

### Area of your issue?

general usage

### What happened

the docker container does not allow to run the image with the --config-path option 

### Steps to reproduce

create a docker compose file 
add 

command: --config-path ./my-config.yaml serve

**Comment by trendsetter37** [comment]
@chris-aeviator Can you post your entire docker-compose file?

**Comment by chris-aeviator** [comment]
```
`
version: 3.9
services:
  chat-registration:
    image: zeratax/matrix-registration:v0.9.1
    volumes:
      - ./:/data
    command: --config-path /data/matrix_registration/config.yaml serve

```
```
